// This file stores detailed information about each teacher.
// You can add or update teacher details here.

const teacherData = {
    // Format: "ABBREVIATION": { fullName: "Full Name", subjects: ["Subject 1", "Subject 2"] }
    "Ahmad": { fullName: "Ahmad Razikki Rosli", subjects: ["Pendidikan Jasmani"] },
    "Aqilah": { fullName: "Nurul Aqilah Humaira Bohari", subjects: ["Bahasa Melayu"] },
    "Arfah": { fullName: "Norarfah Hasim", subjects: ["Fizik", "Sains"] },
    "Azhar": { fullName: "Azhar Bin Selamat", subjects: ["Sejarah"] },
    "Cik Salma": { fullName: "Siti Nur Salma Binti Rizuan", subjects: ["Bahasa Melayu"] },
    "Efa": { fullName: "Efah Suhaila Salamon", subjects: ["Bahasa Melayu"] },
    "Eidayu": { fullName: "Eidayu Binti Mohd Yusof", subjects: ["Matematik"] },
    "Faezah": { fullName: "Nur Faezah Mohd Nori", subjects: ["Matematik Tambahan", "Matematik"] },
    "Faris": { fullName: "Muhammad Faris Bin Mazlan", subjects: ["KKQ", "Pendidikan Islam"] },
    "Fauzi": { fullName: "Fauzi Bin Ishak", subjects: ["Pendidikan Jasmani"] },
    "Gowry": { fullName: "Gowry A/P Sinniah", subjects: ["Sejarah"] },
    "Gurchan": { fullName: "Gurchan Kaur A/P Dharam Singh", subjects: ["Pendidikan Jasmani", "Pendidikan Moral"] },
    "Hajar": { fullName: "Siti Hajar Binti Ismail", subjects: ["Pendidikan Islam", "Tasawwur Islam"] },
    "Hanim": { fullName: "Hanim Suria Hussin", subjects: ["Perniagaan"] },
    "Haslina": { fullName: "Haslina Binti Selamat", subjects: ["Asas Sains Komputer"] },
    "Haziqah": { fullName: "Nurhaziqah Hanim", subjects: ["Bahasa Melayu"] },
    "Imelda": { fullName: "Imelda Binti Bundan", subjects: ["Matematik"] },
    "Iqbal": { fullName: "Iqbal Hareez Osman", subjects: ["Pendidikan Seni Visual"] },
    "Irda": { fullName: "Irda Syuhada Ishak", subjects: ["Bahasa Inggeris"] },
    "Izzah": { fullName: "Nurul Izzah Binti Zainal Abidin", subjects: ["Bahasa Arab"] },
    "Kalai": { fullName: "Kalaivani A/P Ananthanar", subjects: ["Perniagaan", "Pendidikan Jasmani"] },
    "Kartini": { fullName: "Kartini Ya'akub", subjects: ["Sejarah"] },
    "Lau": { fullName: "Lau Lee Lee", subjects: ["Bahasa Cina"] },
    "Lisah": { fullName: "Lisah Binti Saiman", subjects: ["Matematik"] },
    "Malina": { fullName: "Malina Binti Mahpud", subjects: ["Fizik", "Matematik Tambahan"] },
    "Masjuki": { fullName: "Masjuki Bin Rasik", subjects: ["KKQ", "Pendidikan Islam"] },
    "Masrul": { fullName: "Masrulhuda Muhammad", subjects: ["Asas Sains Komputer"] },
    "Masrizan": { fullName: "Masrizan Binti Mohamad", subjects: ["Geografi"] },
    "Nadia": { fullName: "Nadia Binti Abdul Rahman", subjects: ["Bahasa Arab"] },
    "Naza": { fullName: "Nazatul Shima Binti Mohd Naza", subjects: ["Bahasa Melayu"] },
    "Nazri": { fullName: "Mohd Nazri Azis", subjects: ["Sains"] },
    "Nik": { fullName: "Nik Normahizan Yusuf", subjects: ["Pendidikan Seni Visual"] },
    "Nivetha": { fullName: "Nivetha A/P Balakrishnan", subjects: ["Bahasa Inggeris"] },
    "Norosniza": { fullName: "Norosniza Osman", subjects: ["Biologi", "Sains"] },
    "Nura": { fullName: "Nura Binti Abdul Rahim", subjects: ["Bahasa Inggeris"] },
    "Nurain": { fullName: "Siti Nurain Asman", subjects: ["Geografi", "Pendidikan Jasmani"] },
    "Nurashidah": { fullName: "Nurashidah Binti Abdul Rashid", subjects: ["Matematik Tambahan"] },
    "Qalilah": { fullName: "Siti Qalilah Radin", subjects: ["Kimia", "Sains"] },
    "Raihah": { fullName: "Raihah Rosli", subjects: ["Matematik"] },
    "Ridzuwan": { fullName: "Ridzuwan Bin Hassan", subjects: ["Sejarah", "Pendidikan Jasmani"] },
    "Rosieati": { fullName: "Rosieati Binti Othman", subjects: ["Sejarah"] },
    "Roslina": { fullName: "Roslina Binti Mohd Ali", subjects: ["Sains", "RBT"] },
    "Rozali": { fullName: "Rozali Bin Zakaria", subjects: ["Sains"] },
    "Ruhazana": { fullName: "Ruhazana Che Musa", subjects: ["Tasawwur Islam", "Bahasa Melayu"] },
    "Saraswadi": { fullName: "Saraswadi A/P Raman", subjects: ["Pendidikan Seni Visual", "Bahasa Tamil"] },
    "Shah": { fullName: "Shah Bin Abdul Rahman", subjects: ["Pendidikan Seni Visual"] },
    "Sharul": { fullName: "Sharul Anuar Md Arif", subjects: ["Pendidikan Moral", "Pendidikan Jasmani", "RBT"] },
    "Suhaila": { fullName: "Suhaila Binti Mohd Lassim", subjects: ["Sains"] },
    "Syamimi": { fullName: "Nur Syamimi Mohd Shafie", subjects: ["Kimia", "Matematik"] },
    "Theva": { fullName: "Thevandran A/L Bathumalai", subjects: ["Bahasa Inggeris"] },
    "Tillaga": { fullName: "Tillaga A/P Subramaniam", subjects: ["Bahasa Inggeris"] },
    "Wan Hafez": { fullName: "Wan Hafez Bin Wan Hassan", subjects: ["Pendidikan Jasmani", "Bahasa Inggeris"] },
    "Zuhdah": { fullName: "Zuhdah Binti Husin", subjects: ["Pendidikan Islam"] },
    "Zuraiha": { fullName: "Zuraiha Binti Abd Wahab", subjects: ["Bahasa Melayu", "Sejarah"] },
    "Zurina": { fullName: "Zurina Binti Abd Jamil", subjects: ["Bahasa Inggeris"] },
    "Zuraidah": { fullName: "Siti Zuraidah Mohd Kadis", subjects: ["Matematik", "Matematik Tambahan"] }
};

