const teacherData = {
    "ABD AZIZ": { fullName: "ABD AZIZ", subjects: ["PH", "T&T", "KOKO"] },
    "ZURAIHA": { fullName: "ZURAIHA", subjects: ["PH", "BM", "SJ", "KOKO"] },
    "FAUZI": { fullName: "FAUZI", subjects: ["PH", "PL", "MM", "MMT", "PJ", "KOKO"] },
    "WAN HAFEZ": { fullName: "WAN HAFEZ", subjects: ["PH", "PJ", "BI", "KOKO"] },
    "ZURINA": { fullName: "ZURINA", subjects: ["PH", "BI", "PIB", "KOKO"] },
    "GOWRY": { fullName: "GOWRY", subjects: ["PH", "RP", "SJ", "IS", "KOKO"] },
    "IMELDA": { fullName: "IMELDA SURIA", subjects: ["PHP", "MM", "PJ", "PL", "KOKO"] },
    "ROSLINA": { fullName: "ROSLINA", subjects: ["PH", "SN", "RBT", "PB", "IM", "KOKO"] },
    "AHMAD": { fullName: "AHMAD RAZIKKI", subjects: ["PH", "PJ", "SJ", "IM", "PL", "KOKO"] },
    "AZHAR": { fullName: "AZHARUDIN", subjects: ["PH", "SJ", "PJ", "BL", "KOKO"] },
    "EIDAYU": { fullName: "EIDAYU", subjects: ["PH", "MM", "PL", "KOKO"] },
    "EFAH": { fullName: "EFAH SUHAILA", subjects: ["PH", "BM", "KOKO"] },
    "GURCHAN": { fullName: "GURCHAN KAUR", subjects: ["PH", "PJ", "PA", "KOKO"] },
    "HANIM": { fullName: "HANIM SURIA", subjects: ["PH", "PNG", "KOKO"] },
    "HASLINA": { fullName: "HASLINA", subjects: ["PH", "AS", "PI", "KOKO"] },
    "IQBAL": { fullName: "IQBAL HAREEZ", subjects: ["PH", "PS", "PJ", "BS", "KOKO"] },
    "IRDA": { fullName: "IRDA SYUHADA", subjects: ["PH", "BI", "LE", "KOKO"] },
    "KALAI": { fullName: "KALAIVANI", subjects: ["PH", "PNG", "PM", "PJ", "KOKO"] },
    "KARTINI": { fullName: "KARTINI", subjects: ["PH", "SJ", "PM", "PL", "KOKO"] },
    "LAU": { fullName: "LAU SHI YIN", subjects: ["PH", "IV", "PJ", "BC", "B DIGITAL", "KOKO"] },
    "MALINA": { fullName: "MALINA", subjects: ["PH", "IV", "MM", "FIZ", "BL", "KOKO"] },
    "MASJUKI": { fullName: "MASJUKI", subjects: ["PH", "KKQ", "BA", "PI", "KOKO"] },
    "MASRIZAN": { fullName: "MASRIZAN", subjects: ["PH", "GE", "RB", "PB", "NILAM", "KOKO"] },
    "MASRUL": { fullName: "MASRULHUDA", subjects: ["PH", "BI", "IB", "ASK", "CT", "OPT", "LE", "KOKO"] },
    "LISAH": { fullName: "MASRULISAH", subjects: ["PH", "MM", "MMT", "PL", "KOKO"] },
    "NAZRI": { fullName: "MOHD NAZRI", subjects: ["PH", "SN", "KOKO"] },
    "RIDZUAN": { fullName: "MOHD RIDZUAN", subjects: ["PH", "SJ", "PJ", "PM", "PL", "KOKO"] },
    "ROZALI": { fullName: "MOHD ROZALI", subjects: ["PH", "SN", "KOKO"] },
    "NAZA": { fullName: "NAZARIAH", subjects: ["PH", "BM", "KOKO"] },
    "NIK": { fullName: "NIK NORMAHIZAN", subjects: ["PH", "PS", "KOKO"] },
    "NIVETHA": { fullName: "NIVETHA", subjects: ["PH", "BI", "E", "KOKO"] },
    "ARFAH": { fullName: "NORARFAH", subjects: ["PH", "SN", "FIZ", "KOKO"] },
    "NOROSNIZA": { fullName: "NOROSNIZA", subjects: ["PH", "SN", "BIO", "TV", "KOKO"] },
    "SYAMIMI": { fullName: "NUR SYAMIMI", subjects: ["PH", "MM", "IM", "KI", "KIM", "KOKO"] },
    "NURA": { fullName: "NURA", subjects: ["PH", "BI", "LE", "KOKO"] },
    "NURASHIDAH": { fullName: "NURASHIDAH", subjects: ["PH", "PD", "MM", "TV", "MMT", "SPIDA", "KOKO"] },
    "HAZIQAH": { fullName: "NURHAZIQAH", subjects: ["PH", "BM", "KOKO"] },
    "AQILAH": { fullName: "NURUL AQILAH", subjects: ["PH", "BM", "KOKO"] },
    "RAIHAH": { fullName: "RAIHAH", subjects: ["PH", "MM", "PL", "KOKO"] },
    "ROSIEATI": { fullName: "ROSIEATI", subjects: ["PH", "SJ", "IS", "PB", "PL", "RBT", "KOKO"] },
    "RUHAZANA": { fullName: "RUHAZANA", subjects: ["P", "BM", "TAW", "RA", "KOKO"] },
    "SARASWADI": { fullName: "SARASWADI", subjects: ["PH", "PS", "PJ", "BT", "PM", "KOKO"] },
    "SHAH": { fullName: "SHAH RIDHA", subjects: ["PH", "SS", "PP", "PS", "KOKO"] },
    "SHARUL": { fullName: "SHARUL ANUAR", subjects: ["PH", "PA", "PJ", "PB", "RBT", "KOKO"] },
    "HAJAR": { fullName: "SITI HAJAR", subjects: ["PH", "B", "PI", "SI", "TAW", "K", "KOKO"] },
    "NADIA": { fullName: "SITI NADIA", subjects: ["PH", "PI", "BA", "KOKO"] },
    "NASUHA": { fullName: "SITI NASUHA", subjects: ["PH", "BM", "HA", "KOKO"] },
    "SALMA": { fullName: "SITI NUR SALMA", subjects: ["PH", "BM", "SJ", "SADM", "KOKO"] },
    "NURAIN": { fullName: "SITI NURAIN", subjects: ["PH", "PJ", "GE", "KOKO"] },
    "QALILAH": { fullName: "SITI QALILAH", subjects: ["PH", "KIM", "SN", "N", "R", "KOKO"] },
    "ZURAIDAH": { fullName: "SITI ZURAIDAH", subjects: ["PH", "IM", "MMT", "MM", "PL", "KOKO"] },
    "SUHAILA": { fullName: "SUHAILA", subjects: ["PH", "LA", "SN", "KOKO"] },
    "THEVA": { fullName: "THEVANDRAN", subjects: ["PH", "BI", "KOKO"] },
    "TILLAGA": { fullName: "TILLAGA", subjects: ["PHD", "BI", "D", "AE", "KOKO"] },
    "ZUHDAH": { fullName: "ZUHDAH", subjects: ["PH", "PI", "UBI", "KOKO"] },
    "NABIHAH": { fullName: "NURUL NABIHAH", subjects: ["PH", "KOKO"] },
    "FAEZAH": { fullName: "NUR FAEZAH", subjects: ["PHIM", "MM", "MMT", "PL", "KOKO"] },
    "FARIS": { fullName: "MUHAMMAD FARIS", subjects: ["PH", "KKQ", "PI", "AZ", "KOKO"] },
    "IZZAH": { fullName: "WAN NURUL IZZAH", subjects: ["PH", "BA", "KOKO"] },
    "ASIAH": { fullName: "ASIAH", subjects: ["PH", "KOKO"] },
    "FARIZA": { fullName: "NURFARIZA", subjects: [] },
    "AZIZ": { fullName: "AZIZ", subjects: [] }
};


